title: linux/hub
description: Guide curate e dettagliate sul mondo Linux ed Open source. Trattiamo nello specifico argomenti a scopo educativo.
author: linuxhub.it Team
email: send@mirko.pm
url: https://linuxhub.it

assets: /assets
uploads: /uploads

permalink: /articles/:title/
markdown: kramdown

paginate: 5
paginate_path: "/:num/"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

navigation:
    - link: "/"
      name: Home

    - link: "https://t.me/linuxpeople"
      name: Community

    - link: "https://linuxpeople.org"
      name: "linuxpeople"

    - link: "https://feeds.linuxpeople.org"
      name: "Tricks"
      icon: "auto_fix_high"
      
    - link: "https://github.com/linuxhubit/linuxhub.it"
      name: "Scrivi"
      icon: "add_box"
      color: "#00c36b"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap